version: '3'

services:

  app:
    build: .
    container_name: nestjs-auth-prisma-sqlite-app
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app